### ISSUE TITLE
Use huggingface implementation

### ISSUE THREAD

**Issue by tadejsv** [jina-ai/executor-clip-image#29]
This repository should switch from OpeanAI's to Huggingface's [implementation](https://huggingface.co/transformers/model_doc/clip.html) of the model. This has several benefits
- The transformers library is professionally developed and maintained - meaning us and the users can rely on it more. OpenAI's implementation is just research paper demonstration, with little resources allocated to continued development and maintenance.
- Transformers library integrates with huggingface model hub, where custom versions of the model can be published - several [already exist](https://huggingface.co/models?search=clip) for CLIP. Users would appreciate the option to use custom model more suitable for their use case
- Users training custom models will do so using the transformers library, which has a well developed training interface (OpeanAI's has none). Meaning that if we want to enable users to use their own custom models, we must use huggingface's implementation.

Since the default weights (ViT 32) are present in both implementations, there should be zero switching downside for existing users.

**Comment by CatStark** [comment]
Moved to https://github.com/jina-ai/executors/issues/10
